### ISSUE TITLE
Chaos Legion hit

### ISSUE THREAD

**Issue by Macpayne** [chief-gant/SplinterlandsTraderBot#1]
Turned on the bot and was running it after Chaos Legion hit tonight, the bot found a gold foil chaos legion card Hill Giant, bought it, listed it and was starting a new iteration when this error happened which I believe is just a nothing is classified as Chaos Legion yet error.  Thank you for the time on this bot, and the DEC that follows.
 Starting iteration
Parameters:{'check_interval': 0, 'fixed_price_interval': 300, 'minimum_balance': 0, 'min_abs_gain': 0.1, 'min_rel_gain': 0.1, 'min_post_number': 10}
Balance: $1.92

Found offer: Ant Miners (Regular)
There was a problem while buying the card, there might be a problem with the offer.
The offer will be excluded from the next iterations.

We match the lowest price of: Goblin Firemage
We match the lowest price of: Goblin Shaman
We match the lowest price of: Charlok Minotaur
Traceback (most recent call last):
  File "splinterlands_trader_bot.py", line 593, in <module>
  File "splinterlands_trader_bot.py", line 584, in run
  File "splinterlands_trader_bot.py", line 504, in update_posts
KeyError: (370, True)

**Comment by Macpayne** [comment]
Not sure what the issue was but its working now.

**Comment by chief-gant** [comment]
Probably the API wasn't returning the info on the Chaos Legion cards yet, but they were already listed. It makes sense for this issue to have solved itself.
